---
title: "Google Trends"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: flatly
---

```{r setup, include=FALSE}
require(here)
source(here::here("/R/packages.r"))

update_data <- TRUE

if (update_data == TRUE) {
  source(here("/R/wrangle.r"))
} else {
  interest_xts <- base::readRDS(here("/data/interest_xts.rds"))
}

# Set global knitr options
knitr::opts_chunk$set(
  include = TRUE,
  echo = FALSE,
  warning = FALSE
)
```

Numbers represent search interest relative to the highest point on the chart for the given region and time. A value of 100 is the peak popularity for the term. A value of 50 means that the term is half as popular. A score of 0 means there was not enough data for this term.

Row {data-height=250}
-------------------------------------
### `r toupper(names(interest_xts)[1])`
```{r}

dygraph(interest_xts[, 1], group = "gtrends") %>%
  dyAxis("y", valueRange = c(0, 101)) %>%
  dyOptions(
    colors = RColorBrewer::brewer.pal(3, "Set2"),
    fillGraph = TRUE,
    fillAlpha = 0.4
  ) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyRangeSelector(height = 30) %>%
  dyLegend(show = "follow")
```

Row {data-height=250}
-------------------------------------
### `r toupper(names(interest_xts)[2])`
y
```{r}
dygraph(interest_xts[, 2], group = "gtrends") %>%
  dyAxis("y", valueRange = c(0, 101)) %>%
  dyOptions(
    colors = RColorBrewer::brewer.pal(3, "Set2"),
    fillGraph = TRUE,
    fillAlpha = 0.4
  ) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyRangeSelector(height = 30) %>%
  dyLegend(show = "follow")
```

Row {data-height=250}
-------------------------------------
### `r toupper(names(interest_xts)[3])`

```{r}
dygraph(interest_xts[, 3], group = "gtrends") %>%
  dyAxis("y", valueRange = c(0, 101)) %>%
  dyOptions(
    colors = RColorBrewer::brewer.pal(3, "Set2"),
    fillGraph = TRUE,
    fillAlpha = 0.4
  ) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyRangeSelector(height = 30) %>%
  dyLegend(show = "follow")
```

Row {data-height=250}
-------------------------------------
### `r toupper(names(interest_xts)[4])`

```{r}
dygraph(interest_xts[, 4], group = "gtrends") %>%
  dyAxis("y", valueRange = c(0, 101)) %>%
  dyOptions(
    colors = RColorBrewer::brewer.pal(3, "Set2"),
    fillGraph = TRUE,
    fillAlpha = 0.4
  ) %>%
  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyRangeSelector(height = 30) %>%
  dyLegend(show = "follow")
```
